# Generated by Django 3.2.4 on 2021-06-14 17:43

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1500)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.blog_data_path)),
                ('author', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('tag', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
